version: '3'

services:
  app:
    image: caotrunghieu/upbase-chatbot-generate-content:v1.0
    ports:
      - "3000:3000"
    environment:
      OPENAI_API_KEY: "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"
    depends_on:
      - db
    networks:
      - my-network
  db:
    image: caotrunghieu/postgres-content-generation:v1.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "242003"
      POSTGRES_DB: content_generation
    expose:
      - 5432
    networks:
      - my-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
networks:
  my-network:
volumes:
  postgres_data: